### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by arnese** [okfde/ifg-self-audit#1]
- [x] Max: Wie sollen wir Self-Audit bei FDS einbinden? Ich würde https://fragdenstaat.de/self-audit/ vorschlagen und dann vielleicht per iframe?
- [x] Max: Grafik / Logo dafür entwerfen
- [x] Arne: Texte für Auswertung
- [x] Arne: Gewichtung für die Fragen

## Technik
- [x] Max: Könnten die eingegebenen Antworten im Local Storage verbleiben? Wenn man auf "Zurück" geht, sind die Antworten weg, oder?
- [x] Max: Gibt es eine Möglichkeit, sich durchzuklicken ohne alle Fragen zu beantworten? Evtl. zwar Fehler anzeigen, aber trotzdem weiter machen können?
- [x] Max: Was könnte man noch mit dem Ergebnis machen außer drucken? Vermutlich mit Mail verschicken?
- [x] Max: Performance verbessern

## Launch Date: 23.2.!

- [x] Max: [Blog Post](https://fragdenstaat.de/blog/2020/12/22/ifg-self-audit/)
- [x] Max und Arne: E-Mail an alle Behörden mit Hinweis auf Self-Audit rausschicken
- [x] Arne: Koordinieren mit Ba-Wü-Beauftragtem
- [ ] Arne: Mail an alle Datenschutzbeauftragten der Länder und des Bundes

**Comment by krmax44** [comment]
hier ein paar Logoentwürfe https://www.figma.com/file/sSUnvETbgKnEtcTXnUFNCn/IFG-Self-Audit-Logo-Entw%C3%BCrfe?node-id=0%3A1

## Random To Dos

- [x] `questionnaire.xlsx` zu den Contractor-Dateien hinzufügen (Arne/Stefan/jemand mit VPN :upside_down_face:)
- [x] die antwortoptionen hab ich eigentlich als joke eingetragen, sollen die bleiben? :upside_down_face: 
      > 1.5.2 Wie viel Wissen zu IFG-Anfragen ist niedergeschrieben?
        > nichts bis wenig 
        > einiges
        > viel
- [x] Verweis auf Behördenguide in die Auswertung (Arne)
- [x] Auf 200 Punkte hoch (Arne)
- [x] XSS per URL nicht möglich, oder?
- [x] Print styles kaputt, fix für django-contractor kommt (Max)
- [x] Guidance wird immer angezeigt wenn nicht die beste Option gewählt wurde. bei der personalfrage kommt also immer "Es sind nicht ausreichend Personalstellen vorgesehen." (außer man nimmt zwischen 5 und 10, was für viele behörden ja totaler overkill ist). vielleicht das anders formulieren? die jetzigen optionen zur frage habe ich übrigens zum testen verwendet und nur nach Bauchgefühl eingetragen ;) (Arne)
- [x] immer gleiche ID für choices, sonst nach Neubuild nicht mehr zuordbar (Max)

## Feedback Lea

- [x] ich bin mir nicht sicher, ob der begriff self-audit gut verständlich ist. gibt es da ein deutsches wort für? selbst-evaluierung oder so? oder einfach checkliste? "audit" ist ja eig eher eine finanzprüfung
- [x] frage 4.2: ablehnungen im plural
- [x] frage 4.7.2: da ist unklar, ob sich die antwort auf "innerhalb der frist" oder "nicht innerhalb der frist" bezieht. und es sollte die option "weniger als 25%" geben
- [x] der excel-download funktioniert bei mir nicht (404)
- [x] man könnte am anfang erwähnen, dass das ergebnis besser ist, wenn man möglichst alle fragen ausfüllt. zum teil ist das eh fies, vlt beantwortet eine behörde anfragen ja immer pünktlich, aber führt keine statistik, sodass sie die frage nicht ausfüllen können :umgekehrtes_gesicht:
- [x] generell sind viele fragen ziemlich suggestiv, was auch daran liegt, dass "ja" immer die "richtige" antwort ist und es deswegen verneinte fragen gibt. ist aber vermutlich für diese zwecke eher unproblematisch, es soll ja auch suggestiv sein und explizit vorschläge machen
